import { FrequencyProvider } from "@/context/frequency.context";
import { TransitionsProvider } from "@/context/transitions.context";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<FrequencyProvider>
					<TransitionsProvider>{children}</TransitionsProvider>
				</FrequencyProvider>
			</body>
		</html>
	);
}
